import { Provider } from '@angular/core';
import { provideNzConfig } from 'ng-zorro-antd/core/config';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import { NZ_I18N, ro_RO } from 'ng-zorro-antd/i18n';
import { IconDefinition } from '@ant-design/icons-angular';
import {
  ArrowLeftOutline,
  CopyOutline,
  MailOutline,
  PhoneOutline,
  UserOutline,
  WarningOutline,
  LoadingOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  InfoCircleOutline,
  ExclamationCircleOutline,
  PlusOutline,
  SearchOutline,
  FilterOutline,
  EnvironmentOutline,
  CalendarOutline,
  ClockCircleOutline,
  ShareAltOutline,
  FacebookOutline,
  TwitterOutline,
  LinkOutline,
  ZoomInOutline,
  PictureOutline,
  SendOutline,
  BankOutline,
  SafetyCertificateOutline,
  ApartmentOutline,
  TeamOutline,
  GlobalOutline,
  CompassOutline,
  ForwardOutline,
  HomeOutline,
  ReloadOutline,
  FileExclamationOutline,
  LeftOutline,
  RightOutline,
  EyeOutline,
  ArrowRightOutline,
  GoogleOutline,
  EyeInvisibleOutline,
  PlusCircleOutline,
  FileTextOutline,
  UserAddOutline,
  LoginOutline,
  LogoutOutline,
  DownOutline,
  SettingOutline,
  NotificationOutline,
  HeartOutline,
  LikeOutline,
  ToolOutline,
  MessageOutline,
  RobotOutline,
  UploadOutline,
  CameraOutline,
  DeleteOutline,
  EditOutline,
  CheckOutline,
  PercentageOutline,
  FieldTimeOutline,
  FlagOutline,
  InboxOutline,
  TrophyOutline,
  CrownOutline,
  StarOutline,
  FireOutline
} from '@ant-design/icons-angular/icons';

export const ngZorroConfig = provideNzConfig({
  theme: {
    primaryColor: '#FCA311',
    infoColor: '#14213D',
    successColor: '#28A745',
    warningColor: '#FCA311',
    errorColor: '#DC3545',
  },
  message: {
    nzTop: 24,
    nzDuration: 3000,
    nzMaxStack: 3,
  },
  notification: {
    nzTop: '24px',
    nzPlacement: 'topRight',
  }
});

const icons: IconDefinition[] = [
  ArrowLeftOutline,
  CopyOutline,
  MailOutline,
  PhoneOutline,
  UserOutline,
  WarningOutline,
  LoadingOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  InfoCircleOutline,
  ExclamationCircleOutline,
  PlusOutline,
  SearchOutline,
  FilterOutline,
  EnvironmentOutline,
  CalendarOutline,
  ClockCircleOutline,
  ShareAltOutline,
  FacebookOutline,
  TwitterOutline,
  LinkOutline,
  ZoomInOutline,
  PictureOutline,
  SendOutline,
  BankOutline,
  SafetyCertificateOutline,
  ApartmentOutline,
  TeamOutline,
  GlobalOutline,
  CompassOutline,
  ForwardOutline,
  HomeOutline,
  ReloadOutline,
  FileExclamationOutline,
  LeftOutline,
  RightOutline,
  EyeOutline,
  ArrowRightOutline,
  GoogleOutline,
  EyeInvisibleOutline,
  PlusCircleOutline,
  FileTextOutline,
  UserAddOutline,
  LoginOutline,
  LogoutOutline,
  DownOutline,
  SettingOutline,
  NotificationOutline,
  HeartOutline,
  LikeOutline,
  ToolOutline,
  MessageOutline,
  RobotOutline,
  UploadOutline,
  CameraOutline,
  DeleteOutline,
  EditOutline,
  CheckOutline,
  PercentageOutline,
  FieldTimeOutline,
  FlagOutline,
  InboxOutline,
  TrophyOutline,
  CrownOutline,
  StarOutline,
  FireOutline
];

export const ngZorroIcons = provideNzIcons(icons);

export const ngZorroI18n: Provider = { provide: NZ_I18N, useValue: ro_RO };