const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const { marked } = require('marked');

const CONTENT_DIR = path.join(__dirname, '..', 'src', 'content', 'guides');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'app', 'generated', 'guide-data.ts');

// Configure marked for clean HTML output
marked.use({
  gfm: true,
  breaks: false,
});

function buildGuides() {
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  if (!fs.existsSync(CONTENT_DIR)) {
    console.warn('[build-guides] No content directory found at', CONTENT_DIR);
    fs.writeFileSync(OUTPUT_FILE, `// AUTO-GENERATED — DO NOT EDIT\nexport interface GuideArticle {\n  slug: string;\n  title: string;\n  description: string;\n  category: string;\n  publishedAt: string;\n  readingTime: string;\n  featured: boolean;\n  htmlContent: string;\n}\n\nexport const GUIDE_ARTICLES: GuideArticle[] = [];\n`);
    return;
  }

  const files = fs.readdirSync(CONTENT_DIR).filter(f => f.endsWith('.md'));

  const articles = files.map(file => {
    const raw = fs.readFileSync(path.join(CONTENT_DIR, file), 'utf-8');
    const { data, content } = matter(raw);
    const htmlContent = marked.parse(content);

    // Estimate reading time (~200 words/min for Romanian)
    const wordCount = content.split(/\s+/).filter(Boolean).length;
    const readingTime = `${Math.max(1, Math.ceil(wordCount / 200))} min citire`;

    return {
      slug: data.slug || file.replace('.md', ''),
      title: data.title || 'Untitled',
      description: data.description || '',
      category: data.category || 'general',
      publishedAt: data.publishedAt || new Date().toISOString().split('T')[0],
      readingTime,
      featured: data.featured || false,
      image: data.image || '',
      htmlContent,
    };
  });

  // Sort: featured first, then by date descending
  articles.sort((a, b) => {
    if (a.featured !== b.featured) return b.featured ? 1 : -1;
    return b.publishedAt.localeCompare(a.publishedAt);
  });

  const output = `// AUTO-GENERATED by scripts/build-guides.js — DO NOT EDIT
// Source: src/content/guides/*.md

export interface GuideArticle {
  slug: string;
  title: string;
  description: string;
  category: string;
  publishedAt: string;
  readingTime: string;
  featured: boolean;
  image: string;
  htmlContent: string;
}

export const GUIDE_ARTICLES: GuideArticle[] = ${JSON.stringify(articles, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`[build-guides] Generated ${articles.length} articles → ${OUTPUT_FILE}`);
}

buildGuides();
